### ISSUE TITLE
npm run build is not generating a tree-shaken build.js

### ISSUE THREAD

**Issue by perrohunter** [Stanko/react-redux-webpack2-boilerplate#2]
I'm trying to get the project to product a more lightweight build, however the output of `npm run build` is about 2.5MB, which is a little bit too much, seems like webpack 2.1 beta 26 broke this

**Comment by Stanko** [comment]
Hey, good catch, I will look into this, do you maybe know where the issue is?

**Comment by Stanko** [comment]
Fixed with the last update, thanks!
