### ISSUE TITLE
Why is hot reload not working?

### ISSUE THREAD

**Issue by developer239** [Stanko/react-redux-webpack2-boilerplate#4]
Nice boilerplate. I was quite happy when I saw working webpack2 setup. But why is hot reload not working?

**Comment by SteveByerly** [comment]
Also seeing this issue. It seems to be working from the console, but nothing's updating. If I run with --hot form the command line, it seems to work, but only full page refresh.

**Comment by developer239** [comment]
What a waste of my time... :/

**Comment by SteveByerly** [comment]
@developer239 it's not an issue with this repo, i think it's a webpack thing. lots of ppl have the same problem, just not a lot of docs on webpack 2 yet.
Can't really complain about something someone did for free.

**Comment by developer239** [comment]
https://www.youtube.com/watch?v=fGqUzrs09vs

**Comment by developer239** [comment]
I am trying not to be too rude but ... when you waste 30 minutes on one repository. When you try 10 repositories. Then you pretty much loose whole afternoon. 

Btw I tried your repo with windows 10, windows 10 ubuntu bash, fedora 25. None of them was working.

This is the repository that helped me in the end:
https://github.com/RyanCCollins/scalable-react-boilerplate/issues/62

**Comment by basti1253** [comment]
@SteveByerly I picked your nice work as a starter and hit some issues. I've forked your stuff and refactored it.
Long story short I've hit some rough edges on react-hot-loader (v3.0.0 beta6). As webpack2 already supports HMR I managed to get HMR working - didn't do much testing, though. It's not really working if there's not an initial error in the JS code.
I changed a lot of stuff under the hood - especially the directory structure now matches https://github.com/facebookincubator/create-react-app

Please let me know if you want my changes upstream and I open a PR.

https://github.com/basti1253/react-redux-webpack2-boilerplate

best regards


Sebastian

**Comment by basti1253** [comment]
@Stanko mixed up repo creator. Pinging you in case you are interested in merging my changes.

**Comment by developer239** [comment]
I managed to create my own React / Redux Hot Boilerplate. There are even hot reloading reducers. Pull requests are welcomed.

https://github.com/developer239/ReactReduxApolloGraphQLHotBoilerplate

**Comment by Stanko** [comment]
@basti1253 sure, it would be great if you can open a PR, I would like to see what you have done.

@developer239 nobody is forcing you to use this code. So, there is no need to be passive aggressive. For a start, you haven't described what is not working. I didn't test it on Windows, as our company works on OSX. Feel free to open a PR if you find the issue and fix it.

**Comment by developer239** [comment]
I am sorry if I seem to be passive agressive. I really just don't care anymore. I realised that there is no such thing as a "_perfect boilerplate_ and that if you want the _perfect boilerplate_  ... you have to create one.

I shared my solution so that I could get a feedback. Also `SteveByerly` seemed to have a similar issue. Hot reload was not working. I had to refresh page manually in order to see some changes.

Thank you for your work anyway.

**Comment by Stanko** [comment]
P.S. Sorry for a late response, for some reason I didn't get any notifications on this

@developer239 just pushed a fix for windows, please try running `npm run start-on-win` and let me know if it works?
