### ISSUE TITLE
how to import scss resources under node_modules?

### ISSUE THREAD

**Issue by senseluo** [Stanko/react-redux-webpack2-boilerplate#6]
Hi @Stanko 
is there a way to let the line below works?
@import "~bootstrap/css/bootstrap";

I tried to tweak but fail :-(

**Comment by Stanko** [comment]
Hi @senseluo,
To include bootstrap and everything that goes with it (icons, fonts...) you'll need to add loaders for everything boostrap is using.

I think these are the extensions you need to handle, maybe even some more.
```
.css
.woff
.ttf
.eot
.svg
```

[This discussion](https://github.com/erikras/react-redux-universal-hot-example/issues/171) can be a good starting point.

Then, when you added all of the webpack loaders, load bootstrap in your`app.js`

```
import 'bootstrap/dist/css/bootstrap.css';
```

I'm going to close this, as it is not really issue with this repo. 

Cheers!

**Comment by Stanko** [comment]
Well, I wasn't lazy, so made you a branch where you can see how to it

https://github.com/Stanko/react-redux-webpack2-boilerplate/tree/module-style-include

You can see all the changes I made on the following commit

https://github.com/Stanko/react-redux-webpack2-boilerplate/commit/b19653c365b209c6f6dec1376fa6fb41e0510b9d 

Hope that is what you are trying to achieve.

**Comment by senseluo** [comment]
thanks @Stanko 😘😘😘
I will have a try really appreciated!
